### DISCUSSION TITLE
New features request: Icon option

### DISCUSSION THREAD

**Discussion by atiburzi** [nicufarmache/lovelace-big-slider-card#1] [Ideas]
Hello @nicufarmache, 
the slider appears to be very nice but, at least for how I should use it, I really need the possibility to customize the entity name and icon (possibly icons depending on the entity state).
However it's already really appreciated.
Thank you!

**Comment by nicufarmache** [comment]
Hello, I will probably add an option to set the icon in the next version. 
The name can already be set using the `name` option like this:

```yaml
type: custom:big-slider-card
entity: light.lamp
name: Bedroom Lamp
```

**Comment by nicufarmache** [comment]
I added the icon option in v1.0.8 
so you can try something like this now
```yaml
type: custom:big-slider-card
entity: light.lamp
name: Bedroom Lamp
icon: mdi:lamp
```
