### ISSUE TITLE
tap_action not supporting data: instead of deprecated service_data:

### ISSUE THREAD

**Issue by jazzyisj** [nicufarmache/lovelace-big-slider-card#34]
https://github.com/home-assistant/frontend/pull/12628

I recently updated my entire UI config to comply with the new standard of using `data:` rather than ` service_data:` for entity actions and discovered that the Big Slider Card has not updated yet to support the new syntax.   It's the only card I've come across so far that doesn't.  Since you link to the [updated documentation](https://www.home-assistant.io/dashboards/actions/), it might lead to some confusion.

**New syntax (doesn't work):**

```
tap_action:
  action: call-service
  service: script.some_script
  data: "some data"
```
**Old syntax (works):**

```
tap_action:
  action: call-service
  service: script.some_script
  service_data: "some data"
```

**Checklist:**

- [ X] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
v1.1.2
