### ISSUE TITLE
Standardization with Tile Card

### ISSUE THREAD

**Issue by nicufarmache** [nicufarmache/lovelace-big-slider-card#38]
### Discussed in https://github.com/nicufarmache/lovelace-big-slider-card/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **jazzyisj** April 17, 2023</sup>
What a great card!   Makes you wonder why the UI dev's didn't do this to the tile card, so intuitive! Thank you!  Looking forward to seeing if you can extend it to other entities (I see a few requests for that).

Would you consider standardizing some of the UI of the big slider card with the hass tile card?  I'd like to be able to use them interchangeably in my UI but the inconsistencies are bothersome.

1. Card background should really have been the standard card background color.  (ha-card-background).  I was able to accomplish this for myself with card_mod, but I think it should come out of the box that way for consistency, allowing the user to customize if desired.

2. Card size - the big slider card height is slightly smaller than a tile card and it looks terrible in a grid when used together.  Haven't been able to figure this one out with card_mod yet.

3. Entity name should not word wrap -> it pushes the secondary text off the card, becomes unreadable, and looks terrible.

4. Icon alignment - the big slider icon has less padding to the left than the tile card icon.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/44064559/232487647-faea1838-359b-4493-901b-cb4f2485e3ba.png">

5. A halo around the entity icon would be great to add a little contrast between the icon and the background when entity is on and for a consistent look with the tile card.  Especially if one uses the state-light-active-color for the slider color.  Also, the icon when no rgb support should also be state-light-active-color, not white for consistency with other hass cards.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/44064559/232492005-26436b57-2dfe-4b77-9dd5-5d65bbc38c2d.png">

6. Personally I would have used the state-light-active-color as the standard active slider color instead of the primary color for consistency with other cards.   Of course easily remedied with the color: option of the slider card, it's just a thought.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/44064559/232491478-51939e2d-d9f5-4bde-a0bd-8eeb4fa9dc5d.png">

7. This is more of a functionality request.  I have several timed lights in my home.  Currently I display any active light timers in a separate card (see screenshot).  I'd love to be able to put those timers in the secondary text slot somehow.

<img width="166" alt="Screenshot 2023-04-17 090959" src="https://user-images.githubusercontent.com/44064559/232494627-377f8de1-16d6-4e4a-aa9e-46f1c5b742ec.png">

Thanks again for the great card.  It really gave my lighting dashboard a fresh new look!

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/44064559/232495075-b124408e-caa7-43f3-b840-88ff5f083e37.png">
</div>

**Comment by Lx** [comment]
+1 from me for the icon/text alignment especially, so that things align nicely among other Tile elements:

![image](https://github.com/nicufarmache/lovelace-big-slider-card/assets/160164/fc3b34b8-9931-4fdc-afc7-3db734a9e908)

I guess I would also love it if the bold font was “a little less bold” so that matched that of the Tile cards!

**Comment by jensrossbach** [comment]
It would also be nice to have the slider bar look like the one from tile cards and more-info dialogs (i.e., have rounded corners and a small drag bar).

**Comment by s-hutter** [comment]
To nicely integrate with my dashboard, I have tried using [Card Mod](https://github.com/thomasloven/lovelace-card-mod) to match the Big Slider style to the Tile card.

While the CSS code is not perfect, I am quite happy with the result:
![bigslider-tilestyle](https://github.com/nicufarmache/lovelace-big-slider-card/assets/21988253/f6351b35-a870-4032-9ec9-25131328baab)
_Big Slider Card vs Tile Card, on/off, default light/dark theme. Other themes should work as well, but results might vary._

Here is the code:
```css
type: grid
square: false
columns: 2
cards:
  - type: custom:big-slider-card
    entity: light.couch
    name: Couch
    icon: mdi:sofa-outline
    show_percentage: true
    height: 66
    colorize: true
    background_color: var(--card-background-color)
    border_radius: 12px
    border_color: var(--divider-color)
    card_mod:
      style: |
        #container {
          cursor: col-resize;
        }
        #slider {
          opacity: 0.2 !important;
          filter: none !important;
          background-color: var(--bsc-entity-color) !important;
        }
        #icon {
          margin: auto 0 auto -12px;
          border: 3px solid rgba(158, 158, 158, 0.1);
          border-radius: 100%;
          box-sizing: border-box;
          -moz-box-sizing: border-box;
          -webkit-box-sizing: border-box;
          width: 40px;
          height: 40px;
          filter: none !important;
        }
        #icon[data-state="off"] {
          color: rgb(158, 158, 158);
          border: none;
          background-color: rgba(158, 158, 158, 0.2);
        }
        #content {
          padding:12px 12px 12px 64px !important;
        }
        #name {
          font-weight: 500;
          font-size: 14px;
          line-height: 20px;
          letter-spacing: 0.1px;
        }
        #percentage {
          font-weight: 400;
          font-size: 12px;
          line-height: 16px;
          letter-spacing: 0.4px;
          color: var(--primary-text-color) !important;
        }
  - type: tile
    entity: light.bedroom_ceiling
    name: Bedroom
    icon: mdi:bed-empty
    tap_action:
      action: toggle
    hold_action:
      action: more-info
```

Note that for both cards to behave the same way on tap and hold, you will have to adjust the actions on the standard tile card.

PS: @nicufarmache an official standardization would still be very welcome. Feel free to use the code above however you wish in case it is helping with the implementation.

**Comment by 532910** [comment]
not sure if this is the same issue or should be a separate one, but big-slider-card looks ugly, due to radius inconsistency:
![image](https://github.com/nicufarmache/lovelace-big-slider-card/assets/14617699/ea917904-cadd-4961-9c10-edb8c6657495)

**Comment by david-kalbermatten** [comment]
Inspired by @s-hutter, I set out to create something that is as close as possible to the Tile Card. However, I came across an issue where the color behind var(--bsc-color) is `#FFFFFF` if the light entity only supports brightness adjustment. This is inconnsistent with what the Tile Card uses for the default color which is `var(--state-light-on-color, var(--state-light-active-color, var(--state-active-color)))`. 

Maybe someone out there finds this usefull for their dashboards...

So, I ended up making two versions. One for lights with adjustable color (-temperature) and one for cards that only have brightness:

_the only thing that I couldn't figure out was the part with the `text-overflow: ellipsis;`. Couldn't get it to work quite right._

**Colored Version**:
![image](https://github.com/nicufarmache/lovelace-big-slider-card/assets/45201085/2845df98-43b9-45f1-8ea9-158c55226df2)

```yaml
type: custom:big-slider-card
entity: light.ceiling_lamp
height: auto
colorize: true
show_percentage: true
background_color: var(--card-background-color)
border_radius: 12px
border_width: var(--ha-card-border-width, 1px);
card_mod:
  style: |
    :host {
      --brightness-only-color: var(--state-light-on-color, var(--state-light-active-color, var(--state-active-color)));
      --colorable-color: var(--bsc-entity-color);
      --main-color: var(--colorable-color);
      --slider-bg-opacity: 0.1;
      --icon-bg-color: color-mix(in srgb, var(--main-color), var(--card-background-color) 80%);
    }
    :host([pressed]) {
      --slider-bg-opacity: 0.39;
      --icon-bg-color: color-mix(in srgb, var(--main-color), color-mix(in srgb, var(--main-color) 11%, transparent) 90%);
    }
    #slider {
      opacity: var(--slider-bg-opacity) !important;
      filter: none !important;
      background-color: color-mix(in srgb, var(--main-color) 40%, transparent) !important;
    }
    #icon {
      color: var(--main-color) !important;
      margin: auto 0 auto -12px;
      background-color: var(--icon-bg-color);
      border-radius: 100%;
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      width: 40px;
      height: 40px;
      filter: none !important;
    }
    #icon[data-state="off"] {
      color: rgb(158, 158, 158) !important;
      border: none;
      background-color: rgba(158, 158, 158, 0.2);
    }
    #content {
      padding:12px 12px 12px 64px !important;
      min-width: 0px !important;
    }
    #name {
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      letter-spacing: 0.1px;
      color: var(--primary-text-color);
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
    }
    #percentage {
      font-weight: 400;
      font-size: 12px;
      line-height: 16px;
      letter-spacing: 0.4px;
      color: var(--primary-text-color) !important;
    }
```
**Brightness Only Version**:
![image](https://github.com/nicufarmache/lovelace-big-slider-card/assets/45201085/ec1e65b3-259a-4a17-9e91-f294b9a5e319)

```yaml
type: custom:big-slider-card
entity: light.ceiling_lamp
height: auto
colorize: true
show_percentage: true
background_color: var(--card-background-color)
border_radius: 12px
border_width: var(--ha-card-border-width, 1px);
card_mod:
  style: |
    :host {
      --brightness-only-color: var(--state-light-on-color, var(--state-light-active-color, var(--state-active-color)));
      --colorable-color: var(--bsc-entity-color);
      --main-color: var(--brightness-only-color);
      --slider-bg-opacity: 0.1;
      --icon-bg-color: color-mix(in srgb, var(--main-color), var(--card-background-color) 80%);
    }
    :host([pressed]) {
      --slider-bg-opacity: 0.39;
      --icon-bg-color: color-mix(in srgb, var(--main-color), color-mix(in srgb, var(--main-color) 11%, transparent) 90%);
    }
    #slider {
      opacity: var(--slider-bg-opacity) !important;
      filter: none !important;
      background-color: color-mix(in srgb, var(--main-color) 40%, transparent) !important;
    }
    #icon {
      color: var(--main-color) !important;
      margin: auto 0 auto -12px;
      background-color: var(--icon-bg-color);
      border-radius: 100%;
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      width: 40px;
      height: 40px;
      filter: none !important;
    }
    #icon[data-state="off"] {
      color: rgb(158, 158, 158) !important;
      border: none;
      background-color: rgba(158, 158, 158, 0.2);
    }
    #content {
      padding:12px 12px 12px 64px !important;
      min-width: 0px !important;
    }
    #name {
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      letter-spacing: 0.1px;
      color: var(--primary-text-color);
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
    }
    #percentage {
      font-weight: 400;
      font-size: 12px;
      line-height: 16px;
      letter-spacing: 0.4px;
      color: var(--primary-text-color) !important;
    }
```
Edit: added slider pressed state

**Comment by xvlw** [comment]
I appreciate everyone's contribution here, this helped me close to what im trying to do.

The last piece of the puzzle would be to change the background color of the card to be a different color when the entity state is "off"

I tried the below which mimics the `#icon[data-state="off"]` CSS above but for `background_color` without any effect. Does the background_color need to be a defined CSS value under card_mod before I can introduce the `[data-state="off"]` variable or am I missing the mark completely.

```
#background_color[data-state="off"] {
  color: #272a2c !important;
}
```
How it looks when the light is on

![d4oOcXs](https://github.com/nicufarmache/lovelace-big-slider-card/assets/85139690/d7174736-bd69-4e61-882c-aeaf7d9165e5)

How I want it to look when the light is off
![OrcCJXQ](https://github.com/nicufarmache/lovelace-big-slider-card/assets/85139690/259403d6-3f16-4f97-a417-c8643088c9e4)



Full code below


```
type: custom:big-slider-card
entity: light.air
attribute: brightness
icon: m3s:lightbulb-outlined-filled
background_color: '#4f462a'
colorize: true
show_percentage: true
height: 88
card_mod:
  style: |
    :host {
      --brightness-only-color: var(--state-light-on-color, var(--state-light-active-color, var(--state-active-color)));
      --colorable-color: var(--bsc-entity-color);
      --main-color: var(--colorable-color);
      --slider-bg-opacity: 0.1;
      --icon-bg-color: color-mix(in srgb, var(--main-color), var(--card-background-color) 80%);
    }
    :host([pressed]) {
      --slider-bg-opacity: 0.39;
      --icon-bg-color: color-mix(in srgb, var(--main-color), color-mix(in srgb, var(--main-color) 11%, transparent) 90%);
    }
    #slider {
      opacity: var(--slider-bg-opacity) !important;
      filter: none !important;
      background-color: color-mix(in srgb, var(--main-color) 90%, transparent) !important;
    }
    #icon {
      color: #ffecb3 !important;
      margin: auto 0 auto -12px;
      border-radius: 100%;
      box-sizing: border-box;
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      width: 40px;
      height: 40px;
      filter: none !important;
    }
    #icon[data-state="off"] {
      color: #fddf7e !important;
      border: none;
    }
    #background_color[data-state="off"] {
      color: #272a2c !important;
    }
    #content {
      padding:12px 12px 12px 64px !important;
      min-width: 0px !important;
    }
    #name {
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      letter-spacing: 0.1px;
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
      color: #ffecb3 !important;
    }
    #percentage {
      font-weight: 500;
      font-size: 12px;
      line-height: 16px;
      letter-spacing: 0.4px;
      color: #ffecb3 !important;
    }
```

**Comment by s-hutter** [comment]
> The last piece of the puzzle would be to change the background color of the card to be a different color when the entity state is "off"
> I tried the below which mimics the `#icon[data-state="off"]` CSS above but for `background_color` without any effect.

You used "background-color" as a selector, but it should be a property. "Color" only affects the text color.
To change the background you can target the ha-card element. Unfortunately, this doesn't have anything like the handy "data-state" attribute, but you can use Jinja templates in Card Mod:

```css
card_mod:
  style: |
    {% if states('light.air') == 'off' %}
      ha-card {
        background-color: #272a2c !important;
      }
    {% endif %}
```
